spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

account.keycloak.url=${KEYCLOAK_URL:http://keycloak:8080}
account.keycloak.realm=${KEYCLOAK_REALM:fiap-car-sales}
account.keycloak.client-id=${KEYCLOAK_CLIENT_ID:account-api}
account.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${account.keycloak.url}/realms/${account.keycloak.realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${account.keycloak.url}/realms/${account.keycloak.realm}/protocol/openid-connect/certs

account.frontend-origin=${FRONTEND_ORIGIN:http://localhost}
account.password-recovery-url=${PASSWORD_RECOVERY_URL:http://localhost/password-recovery}
account.resend.api-key=${RESEND_API_KEY:}
account.resend.from=${RESEND_FROM:no-reply@fiapf3.local}

account.bootstrap.admin.enabled=true
account.bootstrap.admin.email=${ACCOUNT_BOOTSTRAP_ADMIN_EMAIL:admin@fiap-car-sales.com}
account.bootstrap.admin.password=${ACCOUNT_BOOTSTRAP_ADMIN_PASSWORD:Fiapf3Admin!}
account.bootstrap.admin.full-name=${ACCOUNT_BOOTSTRAP_ADMIN_FULL_NAME:Platform Admin}

account.s2s.allowed-client-ids=${ACCOUNT_S2S_ALLOWED_CLIENT_IDS:dealership-api}
